### ISSUE TITLE
please make help to run it

### ISSUE THREAD

**Issue by branchmaster** [Ananto30/hadith-every-hour#1]
hi Ananto,
please help me , how to run my own build from zero to hero,
waiting for your response
finest regards

**Comment by Ananto30** [comment]
The process is pretty easy. You just need your own API secrets and tokens for Twitter and Facebook and set them in the environment variable. Then just run the `main.py`. The book and hadith number are tracked in the `hadith_track.json` file. The Hadith API is also hosted by me, so please don't spam it.
You can follow the Github workflow for setting up the project on your own. https://github.com/Ananto30/hadith-every-hour/blob/main/.github/workflows/tweet_hadith.yml

**Comment by Ananto30** [comment]
No reply from @branchmaster , closing this.
